export const types = Object.freeze({
  GET_CURRENCY: 'GET_CURRENCY',
  GET_CURRENCY_SUCCESS: 'GET_CURRENCY_SUCCESS',
  GET_CURRENCY_ERROR: 'GET_CURRENCY_ERROR',
  GET_CURRENCY_RANGE: 'GET_CURRENCY_RANGE',
  GET_CURRENCY_RANGE_SUCCESS: 'GET_CURRENCY_RANGE_SUCCESS',
  GET_CURRENCY_RANGE_ERROR: 'GET_CURRENCY_RANGE_ERROR',
  FILTER_CURRENCY: 'FILTER_CURRENCY',
  ABORT_FILTER_CURRENCY: 'ABORT_FILTER_CURRENCY',
  SET_BASE_CURRENCY: 'SET_BASE_CURRENCY',
  CALCULATE_CURRENCY: 'CALCULATE_CURRENCY',
  SET_ACTIVE_CURRENCY_LIST: 'SET_ACTIVE_CURRENCY_LIST'
})