export const types = Object.freeze({
  GET_CURRENCY: 'GET_CURRENCY',
  GET_CURRENCY_SUCCESS: 'GET_CURRENCY_SUCCESS',
  GET_CURRENCY_ERROR: 'GET_CURRENCY_ERROR',
  FILTER_CURRENCY: 'FILTER_CURRENCY',
  ABORT_FILTER_CURRENCY: 'ABORT_FILTER_CURRENCY'
})