export const types = Object.freeze({
  GET_CURRENCY: 'GET_CURRENCY',
  GET_CURRENCY_SUCCESS: 'GET_CURRENCY_SUCCESS',
  GET_CURRENCY_ERROR: 'GET_CURRENCY_ERROR',
  FILTER_CURRENCY: 'FILTER_CURRENCY',
  ABORT_FILTER_CURRENCY: 'ABORT_FILTER_CURRENCY',
  SET_BASE_CURRENCY: 'SET_BASE_CURRENCY',
  CALCULATE_CURRENCY: 'CALCULATE_CURRENCY',
  CALCULATE_CURRENCY_REVERSE: 'CALCULATE_CURRENCY_REVERSE',
  SET_ACTIVE_CURRENCY_LIST: 'SET_ACTIVE_CURRENCY_LIST',
  SET_ACTIVE_CURRENCY_LIST_WITH_STORAGE: 'SET_ACTIVE_CURRENCY_LIST_WITH_STORAGE'
})