export const types = Object.freeze({
  GET_CURRENCY_RANGE: 'GET_CURRENCY_RANGE',
  GET_CURRENCY_RANGE_SUCCESS: 'GET_CURRENCY_RANGE_SUCCESS',
  GET_CURRENCY_RANGE_ERROR: 'GET_CURRENCY_RANGE_ERROR',
  SET_DATE_RANGE: 'SET_DATE_RANGE'
})